# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - Danalyst

on:
  push:
    branches:
      - azure
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18.x" # Asegúrate de que sea 18.x para compatibilidad

      - name: npm install with legacy peer deps and build
        run: |
          npm install --legacy-peer-deps
          npm run build --if-present
        # Puedes añadir "npm run test --if-present" si tienes pruebas configuradas

      - name: Optimize deployment size
        run: |
          # Eliminar archivos innecesarios de la build para reducir el tamaño del artefacto
          # Nota: Estos comandos son para Windows (rmdir /s /q y del /s /q)
          if exist .next\cache rmdir /s /q .next\cache || echo "Cache folder not found or already removed"
          if exist .next\server\chunks\*.js.map del /s /q .next\server\chunks\*.js.map || echo "Source maps not found or already removed"
          if exist .next\static\chunks\*.js.map del /s /q .next\static\chunks\*.js.map || echo "Source maps not found or already removed"
          if exist .next\types rmdir /s /q .next\types || echo "Types folder not found or already removed"
          # La carpeta node_modules NO se incluye directamente en el artefacto si 'path' es .next/
          # pero si se limpia antes de build localmente para desarrollo, es útil.

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .next/ # <--- ¡IMPORTANTE! Solo sube el output de la build optimizada

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Esto es requerido para solicitar el JWT
      contents: read # Esto es requerido para actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v1 # <--- ¡IMPORTANTE: CAMBIADO A v1 para usar creds!
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # <--- ¡IMPORTANTE: USA EL SECRETO AZURE_CREDENTIALS!

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "Danalyst"
          slot-name: "Production"
          package: . # Esto es correcto porque el artefacto descargado será el contenido de .next/
