// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/layout/navbar"; // <-- Importa la Navbar

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App", // Considera cambiar esto a algo más descriptivo del sitio
  description: "Generated by create next app", // Considera cambiar esto
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es"> {/* Cambiar lang a español */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`} // Añadir min-h-screen
      >
        <Navbar /> {/* <-- Coloca la Navbar aquí, antes del contenido de la página */}
        <div className="flex-1"> {/* Contenedor para que el contenido principal ocupe el espacio restante */}
          {children} {/* <-- El contenido de cada página se renderizará aquí */}
        </div>
      </body>
    </html>
  );
}